#theme: jekyll-theme-minimal
title: Annemarie Timmers
logo: "/images/profile.jpeg"

navbar-links:
  About: "about"
  Experience: "experience"
  Contact: "contact"
  
social_media:
  github: agjtimmers
  linkedin: annemarie-timmers
  
share-links-active:
  linkedin: true

plugins:
  - jekyll-paginate
  - jekyll-sitemap