theme: jekyll-theme-minimal
title: Annemarie Timmers
avatar: "/images/profile.jpeg"

navbar-links:
  About: "about"
  Experience: "experience"
  Contact: "contact"
  

social_media:
  linkedin: annemarie-timmers
